name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: roxsross12
  VERSION: 1.0.0

jobs:

  build-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: donde estoy
      run: pwd
    - name: listado 
      run: ls -lrt
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV    
    - name: Build the Docker image app
      run: |
        cd src/app
        docker build -t frontend:$SHORT_SHA .
        docker images
        docker tag frontend:$SHORT_SHA $REGISTRY/frontend:$SHORT_SHA
        docker push $REGISTRY/frontend:$SHORT_SHA
    - name: Build the Docker image consumer
      run: |
        cd src/consumer
        docker build -t consumer:$VERSION .
        docker images
        docker tag consumer:$SHORT_SHA $REGISTRY/consumer:$SHORT_SHA
        docker push $REGISTRY/consumer:$SHORT_SHA
